import{useEffect,useState}from"react";import{DndContext}from"@dnd-kit/core";import Column from"./components/Column.jsx";import DependencyGraph from"./components/DependencyGraph.jsx";import"./styles.css";
const COLUMNS=["Backlog","In Progress","Review","Done"];const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
async function api(path,opt={}){const res=await fetch(API+path,{headers:{"Content-Type":"application/json"},...opt});if(!res.ok){const b=await res.json().catch(()=>({}));throw Error(b.detail||"Request failed");}return res.json()}
export default function App(){const[tasks,setTasks]=useState([]),[cp,setCp]=useState({path:[],total_duration:0}),[title,setTitle]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[error,setError]=useState(""),[simTask,setSimTask]=useState(""),[days,setDays]=useState(3),[impact,setImpact]=useState(null),[whatIf,setWhatIf]=useState(null),[risks,setRisks]=useState(null),[breakTask,setBreakTask]=useState(""),[breakdown,setBreakdown]=useState(null);
async function refresh(){try{const[a,b]=await Promise.all([api("/board-state"),api("/critical-path")]);setTasks(a);setCp(b);setSimTask(x=>x||a[0]?.id||"");setBreakTask(x=>x||a[0]?.id||"")}catch(e){setError(e.message)}}
useEffect(()=>{refresh()},[]);
async function drag(e){if(!e.over)return;const t=tasks.find(x=>x.id===e.active.id);if(!t||t.column===e.over.id)return;try{await api("/tasks/"+t.id,{method:"PUT",body:JSON.stringify({column:e.over.id})});refresh()}catch(e){setError(e.message)}}
async function addTask(e){e.preventDefault();if(!title.trim())return;const id=title.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-")+"-"+Date.now().toString(36);try{await api("/tasks",{method:"POST",body:JSON.stringify({id,title:title.trim(),duration_days:1})});setTitle("");refresh()}catch(e){setError(e.message)}}
async function addDep(e){e.preventDefault();setError("");if(!from||!to||from===to)return;try{await api("/dependencies",{method:"POST",body:JSON.stringify({from_task_id:from,to_task_id:to})});setFrom("");setTo("");refresh()}catch(e){setError(e.message)}}
async function simulate(e){e.preventDefault();try{const body={method:"POST",body:JSON.stringify({delta_days:Number(days)})};const[a,b]=await Promise.all([api("/tasks/"+simTask+"/shift",body),api("/tasks/"+simTask+"/what-if",body)]);setImpact(a.affected_tasks);setWhatIf(b.explanation)}catch(e){setError(e.message)}}
async function risks(){try{setRisks(await api("/risk-analysis"))}catch(e){setError(e.message)}}
async function breakdownTask(){try{setBreakdown(await api("/tasks/"+breakTask+"/breakdown"))}catch(e){setError(e.message)}}
async function accept(a,b){try{await api("/dependencies",{method:"POST",body:JSON.stringify({from_task_id:a,to_task_id:b})});refresh()}catch(e){setError(e.message)}}
const blocked=tasks.filter(t=>t.status==="Blocked").length;const done=tasks.filter(t=>t.column==="Done").length;const critical=new Set(cp.path);
return <div className="app"><header><div className="eyebrow">DAG-BASED PROJECT SCHEDULING</div><h1>TaskFlow <em>Pro</em></h1><p>Plan dependencies, understand schedule impact, and surface project risk before delays compound.</p></header>{error&&<div className="error">{error}</div>}<div className="metrics"><div><b>{tasks.length}</b><span>Tasks</span></div><div><b>{done}</b><span>Completed</span></div><div><b>{blocked}</b><span>Blocked</span></div><div><b>{cp.total_duration}d</b><span>Critical Path</span></div></div>
<section className="panel"><h2>Critical Path</h2><p>{cp.path.map((id,i)=><span key={id}>{tasks.find(t=>t.id===id)?.title||id}{i<cp.path.length-1?" → ":""}</span>)}</p></section>
<section className="panel"><div className="panel-head"><div><h2>Dependency Map</h2><small>Critical-path nodes are highlighted.</small></div></div>{tasks.length?<DependencyGraph tasks={tasks} criticalPath={cp}/>:<p>No tasks yet.</p>}</section>
<section className="tools"><div className="panel"><h2>Delay Simulation</h2><div className="row"><select value={simTask} onChange={e=>setSimTask(e.target.value)}>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><input type="number" value={days} onChange={e=>setDays(e.target.value)}/><button onClick={simulate}>Simulate</button></div>{impact&&<div className="result">{Object.entries(impact).map(([id,s])=><div key={id}>{tasks.find(t=>t.id===id)?.title}: <b>{s>0?"+":""}{s}d</b></div>)}</div>}{whatIf&&<p className="callout">{whatIf.headline}<br/>{whatIf.recommendation}</p>}</div>
<div className="panel"><h2>AI Risk Analysis</h2><button onClick={risks}>Analyze Risks</button>{risks&&<div/>}{risks&&null}{risks?.risks?.map(r=><div className="risk" key={r.task_id}><b>{r.task_title}</b> · {r.risk_level} {r.score}/100<ul>{r.reasons.map(x=><li key={x}>{x}</li>)}</ul></div>)}</div></section>
<section className="tools"><div className="panel"><h2>AI Task Breakdown</h2><div className="row"><select value={breakTask} onChange={e=>setBreakTask(e.target.value)}>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button onClick={breakdownTask}>Generate</button></div>{breakdown?.subtasks?.map((s,i)=><div className="step" key={i}><b>{i+1}. {s.title}</b><small>{s.reason}</small></div>)}</div><div className="panel"><h2>What-if insight</h2><p className="muted">{whatIf?.headline||"Run a delay simulation to see downstream impact."}</p></div></section>
<div className="panel forms"><form onSubmit={addTask}><input placeholder="New task title" value={title} onChange={e=>setTitle(e.target.value)}/><button>Add Task</button></form><form onSubmit={addDep}><select value={from} onChange={e=>setFrom(e.target.value)}><option value="">Prerequisite</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><span>→</span><select value={to} onChange={e=>setTo(e.target.value)}><option value="">Dependent</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button>Add Dependency</button></form></div>
<DndContext onDragEnd={drag}><div className="board">{COLUMNS.map(c=><Column key={c} column={c} tasks={tasks.filter(t=>t.column===c)} allTasks={tasks} onRequestSuggestions={id=>api("/tasks/"+id+"/suggest-dependencies")} onAcceptSuggestion={accept}/>)}</div></DndContext></div>}